<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error Report - {{ config('APP_NAME', 'Framework') }}</title>
    <style>
        body {
            font-family: "Segoe UI", Roboto, Arial, sans-serif;
            background-color: #f9fafb;
            color: #333;
            margin: 0;
            padding: 30px;
        }

        .container {
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.05);
            padding: 24px;
            max-width: 800px;
            margin: auto;
        }

        h1 {
            color: #e63946;
            font-size: 20px;
            margin-bottom: 10px;
        }

        .meta {
            background: #f3f4f6;
            border-left: 4px solid #e63946;
            padding: 12px 16px;
            margin-bottom: 20px;
            font-size: 14px;
        }

        .trace {
            background: #1e1e1e;
            color: #d4d4d4;
            font-family: "Fira Code", monospace;
            padding: 16px;
            border-radius: 8px;
            white-space: pre-wrap;
            overflow-x: auto;
            font-size: 13px;
        }

        .footer {
            font-size: 12px;
            color: #888;
            text-align: center;
            margin-top: 30px;
        }

        .key {
            color: #555;
            font-weight: bold;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>🚨 Exception Report</h1>

    <div class="meta">
        <div><span class="key">Message:</span> {!! $exception->getMessage() !!}</div>
        <div><span class="key">File:</span> {{ $exception->getFile() }}</div>
        <div><span class="key">Line:</span> {{ $exception->getLine() }}</div>
        <div><span class="key">Date:</span> {{ App\Utilities\Carbon::format('Y-m-d H:i:s') }}</div>
        <div><span class="key">Environment:</span> {{ strtoupper(config('APP_ENV', 'local')) }}</div>
        <div><span class="key">App:</span> {{ config('APP_NAME', 'Framework') }}</div>
    </div>

    <h2 style="font-size:16px; color:#444;">Stack Trace:</h2>
    <div class="trace">{{ $exception->getTraceAsString() }}</div>

    <div class="footer">
        <p>This email was automatically generated by <strong>{{ config('APP_NAME', 'Framework') }}</strong>.</p>
        <p>Please do not reply directly to this message.</p>
    </div>
</div>
</body>
</html>
